# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/EMBEDDED_DESIGN/PID_CONTROL_PROJ1/ece544w24_project_2_rel/Proj2_rel/rvfpganexys.xdc

# Block Designs: bd/embsys/embsys.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys || ORIG_REF_NAME==embsys} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_3/embsys_microblaze_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_3 || ORIG_REF_NAME==embsys_microblaze_0_3} -quiet] -quiet

# IP: bd/embsys/ip/embsys_dlmb_v10_3/embsys_dlmb_v10_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_dlmb_v10_3 || ORIG_REF_NAME==embsys_dlmb_v10_3} -quiet] -quiet

# IP: bd/embsys/ip/embsys_ilmb_v10_3/embsys_ilmb_v10_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_ilmb_v10_3 || ORIG_REF_NAME==embsys_ilmb_v10_3} -quiet] -quiet

# IP: bd/embsys/ip/embsys_dlmb_bram_if_cntlr_3/embsys_dlmb_bram_if_cntlr_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_dlmb_bram_if_cntlr_3 || ORIG_REF_NAME==embsys_dlmb_bram_if_cntlr_3} -quiet] -quiet

# IP: bd/embsys/ip/embsys_ilmb_bram_if_cntlr_3/embsys_ilmb_bram_if_cntlr_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_ilmb_bram_if_cntlr_3 || ORIG_REF_NAME==embsys_ilmb_bram_if_cntlr_3} -quiet] -quiet

# IP: bd/embsys/ip/embsys_lmb_bram_3/embsys_lmb_bram_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_lmb_bram_3 || ORIG_REF_NAME==embsys_lmb_bram_3} -quiet] -quiet

# IP: bd/embsys/ip/embsys_xbar_2/embsys_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_xbar_2 || ORIG_REF_NAME==embsys_xbar_2} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_axi_periph_2/embsys_microblaze_0_axi_periph_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_axi_periph_2 || ORIG_REF_NAME==embsys_microblaze_0_axi_periph_2} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_axi_intc_2/embsys_microblaze_0_axi_intc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_axi_intc_2 || ORIG_REF_NAME==embsys_microblaze_0_axi_intc_2} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_xlconcat_2/embsys_microblaze_0_xlconcat_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_xlconcat_2 || ORIG_REF_NAME==embsys_microblaze_0_xlconcat_2} -quiet] -quiet

# IP: bd/embsys/ip/embsys_mdm_1_2/embsys_mdm_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_mdm_1_2 || ORIG_REF_NAME==embsys_mdm_1_2} -quiet] -quiet

# IP: bd/embsys/ip/embsys_clk_wiz_1_3/embsys_clk_wiz_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_clk_wiz_1_3 || ORIG_REF_NAME==embsys_clk_wiz_1_3} -quiet] -quiet

# IP: bd/embsys/ip/embsys_rst_clk_wiz_1_100M_3/embsys_rst_clk_wiz_1_100M_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_rst_clk_wiz_1_100M_3 || ORIG_REF_NAME==embsys_rst_clk_wiz_1_100M_3} -quiet] -quiet

# IP: bd/embsys/ip/embsys_nexys4io_0_2/embsys_nexys4io_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_nexys4io_0_2 || ORIG_REF_NAME==embsys_nexys4io_0_2} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_timer_0_2/embsys_axi_timer_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_timer_0_2 || ORIG_REF_NAME==embsys_axi_timer_0_2} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_uartlite_0_2/embsys_axi_uartlite_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_uartlite_0_2 || ORIG_REF_NAME==embsys_axi_uartlite_0_2} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_iic_0_3/embsys_axi_iic_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_iic_0_3 || ORIG_REF_NAME==embsys_axi_iic_0_3} -quiet] -quiet

# IP: bd/embsys/ip/embsys_bidirec_0_0/embsys_bidirec_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_bidirec_0_0 || ORIG_REF_NAME==embsys_bidirec_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_bidirec_1_0/embsys_bidirec_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_bidirec_1_0 || ORIG_REF_NAME==embsys_bidirec_1_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_gpio_0_0/embsys_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_0_0 || ORIG_REF_NAME==embsys_axi_gpio_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_gpio_1_0/embsys_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_1_0 || ORIG_REF_NAME==embsys_axi_gpio_1_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_gpio_2_0/embsys_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_2_0 || ORIG_REF_NAME==embsys_axi_gpio_2_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_gpio_3_0/embsys_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_3_0 || ORIG_REF_NAME==embsys_axi_gpio_3_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_gpio_4_0/embsys_axi_gpio_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_4_0 || ORIG_REF_NAME==embsys_axi_gpio_4_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_gpio_5_0/embsys_axi_gpio_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_5_0 || ORIG_REF_NAME==embsys_axi_gpio_5_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_gpio_6_0/embsys_axi_gpio_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_6_0 || ORIG_REF_NAME==embsys_axi_gpio_6_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_gpio_7_0/embsys_axi_gpio_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_7_0 || ORIG_REF_NAME==embsys_axi_gpio_7_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_gpio_8_0/embsys_axi_gpio_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_8_0 || ORIG_REF_NAME==embsys_axi_gpio_8_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_gpio_9_0/embsys_axi_gpio_9_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_9_0 || ORIG_REF_NAME==embsys_axi_gpio_9_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_gpio_10_0/embsys_axi_gpio_10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_10_0 || ORIG_REF_NAME==embsys_axi_gpio_10_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_gpio_11_0/embsys_axi_gpio_11_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_11_0 || ORIG_REF_NAME==embsys_axi_gpio_11_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_gpio_12_0/embsys_axi_gpio_12_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_12_0 || ORIG_REF_NAME==embsys_axi_gpio_12_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_gpio_13_0/embsys_axi_gpio_13_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_13_0 || ORIG_REF_NAME==embsys_axi_gpio_13_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_gpio_14_0/embsys_axi_gpio_14_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_14_0 || ORIG_REF_NAME==embsys_axi_gpio_14_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_tier2_xbar_0_0/embsys_tier2_xbar_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_tier2_xbar_0_0 || ORIG_REF_NAME==embsys_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_tier2_xbar_1_0/embsys_tier2_xbar_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_tier2_xbar_1_0 || ORIG_REF_NAME==embsys_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_tier2_xbar_2_0/embsys_tier2_xbar_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==embsys_tier2_xbar_2_0 || ORIG_REF_NAME==embsys_tier2_xbar_2_0} -quiet] -quiet

# XDC: e:/EMBEDDED_DESIGN/PID_CONTROL_PROJ1/TEST1_VIVADO/project_1/project_1.gen/sources_1/bd/embsys/embsys_ooc.xdc
