# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/EMBEDDED_DESIGN/PID_CONTROL_PROJ1/TEST1_VIVADO/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_3_0/embsys_axi_gpio_3_0.xci
# IP: The module: 'embsys_axi_gpio_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/EMBEDDED_DESIGN/PID_CONTROL_PROJ1/TEST1_VIVADO/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_axi_gpio_3_0/embsys_axi_gpio_3_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_axi_gpio_3_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/EMBEDDED_DESIGN/PID_CONTROL_PROJ1/TEST1_VIVADO/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_axi_gpio_3_0/embsys_axi_gpio_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_axi_gpio_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/EMBEDDED_DESIGN/PID_CONTROL_PROJ1/TEST1_VIVADO/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_axi_gpio_3_0/embsys_axi_gpio_3_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_axi_gpio_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/EMBEDDED_DESIGN/PID_CONTROL_PROJ1/TEST1_VIVADO/project_1/project_1.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_3_0/embsys_axi_gpio_3_0.xci
# IP: The module: 'embsys_axi_gpio_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/EMBEDDED_DESIGN/PID_CONTROL_PROJ1/TEST1_VIVADO/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_axi_gpio_3_0/embsys_axi_gpio_3_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_axi_gpio_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/EMBEDDED_DESIGN/PID_CONTROL_PROJ1/TEST1_VIVADO/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_axi_gpio_3_0/embsys_axi_gpio_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_axi_gpio_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/EMBEDDED_DESIGN/PID_CONTROL_PROJ1/TEST1_VIVADO/project_1/project_1.gen/sources_1/bd/embsys/ip/embsys_axi_gpio_3_0/embsys_axi_gpio_3_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_axi_gpio_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
